#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  8 17:09:09 2020

@author: peter
"""

import os
import numpy as np
from PIL import Image



test = Image.open("germany_covars/CLM_CHE_BIO02.tif")

# dtype = {'F': np.float32, 'L': np.uint8}[test.mode]

# Load the data into a flat numpy array and reshape
np_img = np.array(test.getdata())#, dtype=dtype)
w, h = test.size
np_img.shape = (h, w, np_img.size // (w * h))

np.size(test)
